FROM node:alpine
WORKDIR /usr/src/app/projeto-interdisciplinar-quarto-semestre-gui-main
COPY ./projeto-interdisciplinar-quarto-semestre-gui-main /usr/src/app/projeto-interdisciplinar-quarto-semestre-gui-main
RUN npm install -g @angular/cli
RUN ng serve